on:
  - push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Private Composer Registry
        uses: and-that/private-composer-registry-action@v1.1
        with:
          token: ${{ GITHUB_TOKEN }}          
      - run: |
          git config user.name satis
          git config user.email satis@getcomposer.org
          git add docs/
          git commit -m "Re-built repository assets"
          git push
